#!/bin/bash

CMD=$1
shift 1
ARGS=$@

source .env &> /dev/null || true

_aws() {
  docker run --rm \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_DEFAULT_REGION=us-east-1 \
    -v $PWD:/app xueshanf/awscli\
      aws $@
}

_zip() {
  pushd src
  mkdir ../deploy
  zip -r ../deploy/dist.zip *
  popd
}

deploy() {
  _zip

  set -e
  _aws lambda update-function-code \
    --function-name slackbot \
    --zip-file fileb://app/deploy/dist.zip

  _aws apigateway put-rest-api \
    --rest-api-id g4vlcenksd \
    --body fileb:///app/swagger.json

}

$CMD $ARGS
